- name: Print Information
  hosts: localhost
  vars:
    Name: "Praveen"
    Topic: "Ansible"
  tasks:
    - name: Print Information
      ansible.builtin.debug:
        msg: "Hi My Name is {{Name}} and I am learning {{Topic}}"

    - name: Print Override variable Information
      vars: # Task level variables
        Name: "Naveen"
        Topic: "Shell"
      ansible.builtin.debug:
        msg: "Hi My Name is {{Name}} and I am learning {{Topic}}"
