- name: Print Vars value from Arguments
  hosts: localhost
  tasks:
    - name: Print variable value
      ansible.builtin.debug:
        msg: "Hi My Name is {{Name}} and I am learning {{Topic}}"
# ansible-playbook -i inventory -e ansible_user=ec2-user -e ansible_password=DevOps321 09-vars-args.yaml -e Name=Praveen -e Topic=Ansible
#or
# ansible-playbook -i inventory -e ansible_user=ec2-user -e ansible_password=DevOps321 09-vars-args.yaml -e "Name=Praveen Topic=Ansible"
