- name: Data Types in Ansible
  hosts: web
  vars:
    Course: Devops with AWS # string
    Tools: # list
      - Ansible
      - Terraform
      - Docker
    Experience: # map or dictionary
      Devops: 3
      AWS: 2
    Project: true # boolean

  tasks:
    - name: print
      ansible.builtin.debug:
        msg: "I am Learning {{Course}}, having experience in {{Experience}} and Knowledge on {{Tools}}, having a Project {{Project}}"
