- name: conditions in Ansible
  hosts: web
  become: yes
  tasks:
    - name: check id expense exists or not
      ansible.builtin.command: id expense
      register: USER

    - name: print USER information
      ansible.builtin.debug:
        msg: user information {{USER}}

    - name: say hello
      ansible.builtin.debug:
        msg: "Hello"
