# default variable, uppercase, lowercase, unique, min, max, dic to items, item to dic,

- name: default variable
  hosts: web
  tasks:
  - name: Print value
    ansible.builtin.debug:
      msg: "variable is {{string | default('Hello Praveen')}}"

- name: Minimum and Maximum values
  hosts: web
  vars:
    list: [1, 2, 3, 4, 5]
  tasks: Print Max and Min Value
  - name: Print Max and Min Value from list
    ansible.builtin.debug:
      msg: "Minimum value is {{list | min}} and Maximum value is {{list | max}}"

- name: Convert to Uppercase and Lowercase
  hosts: web
  vars:
    greeting: "Hello Good Morning"
  tasks:
  - name: Print greeting with uppercase and lowercase
    ansible.builtin.debug:
      msg: "greeting in Upper case {{greeting | upper}}"
      msg: "greeting in Upper case {{greeting | lower}}"

- name: Get Unique string from list
  hosts: web
  vars:
    list_of_Numbers: [1,1,,2,3,5,6,6]
  tasks:
  - name: Get Unique string from list
    ansible.builtin.debug:
      msg: "Get unique Number from list {{list_of_Numbers | unique}}"

- name: Convert dictionary to list
  hosts: web
  vars: 
   data_dictionary:
    Name: Praveen
    Topic: Ansible
    Time: 12 hrs
  tasks:
  - name: Convert dictionary to list
    ansible.builtin.debug:
      msg: "Converted List is {{data_dictionary | dic2items}}"

- name: Convert list to dictionary 
  hosts: web
  vars:
    data_list: ['Praveen', 'Naveen']
    data_list2: 
    - {'key': 'Praveen', 'value': 'Ansible'}
    - {'key': 'Naveen', 'value': 'DevOps'}
  tasks:
  - name: Convert dictionary to list
    ansible.builtin.debug:
      msg: "Convert dictionary to list {{data_list}} and 2nd one {{data_list2}}"
