- name: install softwares/packages
  hosts: web
  become: true
  tasks:
    - name: install packages
      ansible.builtin.dnf:
        name: "{ { item } }"
        state: latest
      loop:
        - mysql
        - nginx
        - postfix
