- name:
  hosts: web
  become: yes
  tasks:
    - name: install and Unistall Packages
      ansible.builtin.dnf:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop:
        - { name: "mysql", state: "absent" } # need to as single quotes -->  { name: 'mysql', state: 'absent'}
        - { name: "nginx", state: "latest" }
        - { name: "postfix", state: "absent" }
