- name:
  hosts: web
  become: yes
  tasks:
    - name: install and Unistall Packages
      ansible.builtin.dnf:
        name: "{{item}}"
        state: "{{item}}"
      loop:
        - { name: 'mysql', state: 'absent' }
        - { name: 'nginx', state: 'latest' }
        - { name: 'postfix', state: 'latest' }