- name: shell vs command module
  hosts: localhost
  tasks:
    - name: Excuting from Shell module
      ansible.builtin.shell: "echo 'This is from shell module' > /tmp/shell.txt "

    - name: Executing from Command module
      ansible.builtin.command: "echo 'This is from command module' > /tmp/command.txt"

    # 1. simple commands without the need of shell variables, envrironment and features like redirections, pipes, & go for command module.
    # 2. If we need to run complex commands or scripts go for shell module.
    # 3. Whatever works in command module, it will work in shell module, but vice versa is not true
