- name: Practice Ansible
  hosts: localhost
  become: true
  vars:
    Name: "Praveen"
    Topic: "Ansible"
  tasks:
    - name: Print Name and Topic
      vars:
        Name: "Akash"
        Topic: "Terraform"
      ansible.builtin.debug:
        msg: My Name is {{Name}} and Topic is {{Topic}}
  tasks:
    - name: Install Paskages
      ansible.builtin.dnf:
        name: "{{item}}"
        state: latest
        loop:
          - mysql
          - postgresql
          - fail2ban
          - ncdu